### ISSUE TITLE
 example esp-idf-put not working as expected 

### ISSUE THREAD

**Issue by w2pu** [nopnop2002/esp-idf-smb-client#2]
I have some problems with the example esp-idf-put:
It works fine when compiled without modifications.
`for (int line=0;line<10;line++) {
		sprintf((char *)buf, "This is Text# %d\n", line);
		smb2_write(smb2, fh, buf, strlen((char *)buf));
	}`

If I change the line counter to larger than 10 it doesn't work:
`for (int line=0;line<11;line++) {
		sprintf((char *)buf, "This is Text# %d\n", line);
		smb2_write(smb2, fh, buf, strlen((char *)buf));
	}`

It seems the output should have a length of exactly 16 chars.   No less no more.
Any idea how to adjust this?
I don't understand why but this problem occors when using my Synology NAS share.
The strange thing is that when using a different NAS (SMB on a rpy)  it works als expected?

**Comment by nopnop2002** [comment]
>I don't understand why but this problem occors when using my Synology NAS share.

It seems to be a problem specific to Synology NAS share.

Contact Synology NAS.

**Comment by w2pu** [comment]
For anybody looking for a quick fix:
I found a work around by adjusting the data size that I want to store in multiples of 16.
So it also works with e.g. data size 32,48,64, ....  1024.... etc. 
Thanks
